language: go
go:
  - 1.13.1
script:
  - ./util.sh build
deploy:
  provider: releases
  api_key:
    secure: RYcPk8DZHjE3F6dWaRLOoXsitPu6A2fXeqCm+lTnGde5at6dh1+12uDRmdo6W2hTAqHxmquZ55A+oS1KiKl29IJOX3pRF/ebGGx6DsKZXjrGqSONAmCxxz8Rx0Vuh7pBI2jrJs89tJ1hfb8YykMUNjhnDtFyMuN+wg3OXBa/pVPlBp1VYBy13FePMYWR/G5OaOyMe9VK+uFYsmrJhNqZCAaFm2KRXcL7rDDkRxIWw3Fqcg6GKEj19KI4n2NrOKAobj+LYK7+nd675gKEErYUxbfHKkRTR8SMdkhlrE5KAxTVHkLdaj9+231uouYaJkA83znffT9LRFlBYgyCPmceRpzfU2bqpko42ZIGd583VWU1qiiR/DXeCgLgLaHhK11tnpFexT5kfne7sxsPB8dxRaMbiFmJ+6avhrQr1kun4N+jyuqI47drAw07WfFV+FOFTEu9t29tbDVA2v9sHldAOt7OXEjFT2OmVO4lE9Ydvbeo/LZShcI2otaSVUyxIYji43Ol5H75J+4aMfw7oenS5k5bQDUMwsorHZktWTaoSxQWkg2PbGEGzpMGHWpCHV8zgjydd38KNjRVkIGeRR2pJOhb1lDgP2mmR401vfdweCur9diTHhpVrC4V4tot2ukO9d/5C0bSRvy5qfOl3UlBY4+LvUFoQyGC7ZUy1k56Kag=
  file:
    - pi-temp
  skip_cleanup: true
  on:
    repo: andrewmarklloyd/pi-temp
    tags: true
